version: '3.8'
services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
  node1:
    build: .
    environment:
      - NODE_ID=node1
      - NODE_PORT=8001
      - CLUSTER_ADDRS=http://node1:8001,http://node2:8002,http://node3:8003
      - REDIS_HOST=redis
      - PYTHONUNBUFFERED=1 
      - "8001:8001"
    depends_on:
      - redis
  node2:
    build: .
    environment:
      - NODE_ID=node2
      - NODE_PORT=8002
      - CLUSTER_ADDRS=http://node1:8001,http://node2:8002,http://node3:8003
      - REDIS_HOST=redis
      - PYTHONUNBUFFERED=1  
    ports:
      - "8002:8002"
    depends_on:
      - redis
  node3:
    build: .
    environment:
      - NODE_ID=node3
      - NODE_PORT=8003
      - CLUSTER_ADDRS=http://node1:8001,http://node2:8002,http://node3:8003
      - REDIS_HOST=redis
      - PYTHONUNBUFFERED=1  
    ports:
      - "8003:8003"
    depends_on:
      - redis